class_name CityLots
extends RefCounted
## Altavega lot data (C0 «Escaparate de Altavega», C1 «núcleo urbano»; PLAN v3.8.2 C0 / C1 / C26; doc 09 §4.5): reads
## data/world/city/altavega_lots.json (C1: GENERATED by tools/gen_city.gd from data/world/city/districts.json,
## `city_version` 1 = WorldConst.CITY_VERSION; C0's hand-written v0 is its `fixed` input) and turns it into per-chunk
## items for the streamer. The city is DATA, the same bytes on every client and server (doc 09 §4.4
## «Determinismo»): the layout never depends on the world seed; only the dressing does (the Gran Vía jam: model,
## variant, spacing by hash64(seed, GEN_CITY, jam, lane, slot)). Heights come from the HeightFunction (pure).
##
## Items (Dictionary, metres, world space; `k` = Kind):
##   PODIUM   non-enterable zócalo (CityProcedural building: Base / Roof / ShadowProxy), roof walkable, optional stair
##   TOWER    A1 tower assembled by TowerAssembler (Base + N floor groups + Roof + ShadowProxy) on its podium's roof
##   BRIDGE   one chunk-long segment of the provisional Puente de Hierro (deck profile from the terrain at its ends)
##   VEHICLE  static wreck (A1 car, variant); jam cars carry the seed dressing
##   PROP     street furniture / barriers / lamps (`lamp`: a CityLights lamp at `bulb`)
##   BUILDING C1 family lot (BuildingAssembler: casco / ensanche / bloque / caseta; variant, floors, palette, an
##            enterable ground floor with a KitDoor and loot spawns); base = the highest terrain sample of its footprint
##            (its walls continue `skirt` metres below: a stone plinth on the downhill side)
##   HERO     C1 enterable hero tower (HeroTower: Torre Albo, Edificio Meridiano)
## C1 also indexes per chunk the building footprints (zombie spawns, the scatter clear, the vertical interest filter),
## the painted street segments (roads, sidewalks, plazas) and the clear rects; the street graph and the districts are
## world-level records. Street dressing (the file's `dressing`, per district): street lamps along the roads (layout,
## PROP items built at load from the road segments) and, seeded per world (street_items: hash64(seed, GEN_CITY,
## segment, side, slot)), cars parked along the curbs and furniture on the sidewalks.
## An item belongs to the chunk that contains its centre (a podium is ≤ 52 m: its chunk is always in ring 1 of any
## point of it); the bridge is split per chunk. load_default() must run on the main thread before any ChunkJob
## (World.configure does it); afterwards everything here is read-only and safe from the worker threads.

const PATH := "res://data/world/city/altavega_lots.json"
## Hash generator id of the city ("CITY"): wids and the seeded dressing (PLAN C26: hash64(seed, GEN_CITY, lot, …)).
const GEN_CITY := 0x43495459
enum Kind { PODIUM, TOWER, BRIDGE, VEHICLE, PROP, BUILDING, HERO }
const FACING := {"west": -90.0, "east": 90.0, "north": 180.0, "south": 0.0}
const VARIANTS := ["clean", "snowed", "crashed", "doors", "burnt"]
## Parapet height of the podium roofs (m, CityProcedural) and the stair landing depth.
const PARAPET := 1.1
const LANDING := 3.0

static var _data: Dictionary = {}
static var _loaded: bool = false
static var _problems := PackedStringArray()
static var _file_sha: String = ""
static var _content_sha: String = ""
static var _static_by_chunk: Dictionary = {}     # chunk key -> Array[Dictionary] (layout items, no heights)
static var _chunks_with_jam: Dictionary = {}     # chunk key -> true (a jam lane crosses it)
static var _podiums: Dictionary = {}             # id -> podium record
static var _footprints: Array = []               # [Rect2 (world, axis-aligned bounds), kind] of buildings and vehicles
static var _clear: Array[Rect2] = []
static var _bridge: Dictionary = {}
## C1 per-chunk indices (chunk key -> Array): footprints [PackedVector2Array quad, Kind, id, Rect2 bounds, indoor
## (enterable / hero)], street segments [Vector2 a, Vector2 b, width, kind (0 road, 1 walk, 2 plaza), Rect2 bounds],
## clear rects.
static var _foot_by_chunk: Dictionary = {}
static var _seg_by_chunk: Dictionary = {}
static var _clear_by_chunk: Dictionary = {}
static var _buildings: Dictionary = {}           # id -> BUILDING item (no height)
static var _heroes: Dictionary = {}              # id -> hero record (file)
const SEG_ROAD := 0
const SEG_WALK := 1
const SEG_PLAZA := 2
## Item ids of the street dressing (lamps: + the road segment's row index; parked cars; sidewalk props).
const DRESS_LAMP_ID := 70000
const DRESS_PARK_ID := 79001
const DRESS_PROP_ID := 79002


# ------------------------------------------------------------------ loading
## Loads and validates the lot file once (main thread). False when it is missing or does not validate.
static func load_default() -> bool:
	if _loaded:
		return _problems.is_empty()
	_loaded = true
	if not FileAccess.file_exists(PATH):
		_problems.append("missing %s" % PATH)
		return false
	var bytes := FileAccess.get_file_as_bytes(PATH)
	_file_sha = _sha(bytes)
	var parsed = JSON.parse_string(bytes.get_string_from_utf8())
	if not (parsed is Dictionary):
		_problems.append("%s is not a JSON object" % PATH)
		return false
	_data = parsed
	# content hash: the parsed data re-serialised with sorted keys (line endings / whitespace do not matter)
	_content_sha = _sha(JSON.stringify(_data, "", true, true).to_utf8_buffer())
	_problems = validate(_data)
	if not _problems.is_empty():
		for p in _problems:
			push_error("CityLots: %s" % p)
		return false
	_index()
	return true


static func is_loaded() -> bool:
	return _loaded and _problems.is_empty() and not _data.is_empty()


static func problems() -> PackedStringArray:
	return _problems


static func data() -> Dictionary:
	return _data


## SHA-256 of the file bytes (hex).
static func file_hash() -> String:
	return _file_sha


## SHA-256 of the parsed content with sorted keys (hex): what client and server compare (CRLF checkouts agree).
static func content_hash() -> String:
	return _content_sha


static func city_version() -> int:
	return int(_data.get("city_version", -1))


static func _sha(bytes: PackedByteArray) -> String:
	var hc := HashingContext.new()
	hc.start(HashingContext.HASH_SHA256)
	hc.update(bytes)
	return hc.finish().hex_encode()


static func cm(v) -> float:
	return float(v) / 100.0


static func v2(a) -> Vector2:
	return Vector2(cm(a[0]), cm(a[1]))


static func rect_of(a) -> Rect2:
	var p0 := Vector2(cm(a[0]), cm(a[1]))
	var p1 := Vector2(cm(a[2]), cm(a[3]))
	return Rect2(p0, p1 - p0).abs()


## Problems of a lot file (empty = valid): version, ids, families, groups, references, models.
static func validate(d: Dictionary) -> PackedStringArray:
	var out := PackedStringArray()
	if str(d.get("format", "")) != "altavega_lots":
		out.append("format is not altavega_lots")
	if int(d.get("city_version", -1)) != WorldConst.CITY_VERSION:
		out.append("city_version %s != WorldConst.CITY_VERSION %d" % [d.get("city_version"), WorldConst.CITY_VERSION])
	var ids := {}
	var families: Dictionary = d.get("families", {})
	var models: Dictionary = d.get("models", {})
	var podiums := {}
	for p in d.get("podiums", []):
		podiums[int(p["id"])] = p
	for list_name in ["podiums", "towers", "vehicles", "props", "rows", "jams", "miradores", "camera_zones"]:
		for it in d.get(list_name, []):
			var id := int(it.get("id", -1))
			if id <= 0 or ids.has(id):
				out.append("%s: id %s missing or duplicated" % [list_name, it.get("id")])
			ids[id] = true
	for t in d.get("towers", []):
		var f := str(t.get("family", ""))
		if not families.has(f):
			out.append("tower %s: unknown family %s" % [t["id"], f])
			continue
		if int(t.get("groups", 0)) < int(families[f]["full_groups"]):
			out.append("tower %s: groups %d < the family's %d (only extra floor groups can be stacked)" % [t["id"], int(t["groups"]), int(families[f]["full_groups"])])
		if not podiums.has(int(t.get("on", -1))):
			out.append("tower %s: podium %s not found" % [t["id"], t.get("on")])
	for list_name in ["vehicles", "props", "rows"]:
		for it in d.get(list_name, []):
			if not models.has(str(it.get("model", ""))):
				out.append("%s %s: model %s not in models" % [list_name, it.get("id"), it.get("model")])
	for j in d.get("jams", []):
		for m in j.get("models", {}):
			if not models.has(str(m)):
				out.append("jam %s: model %s not in models" % [j["id"], m])
		for v in j.get("variants", {}):
			if not VARIANTS.has(str(v)):
				out.append("jam %s: unknown variant %s" % [j["id"], v])
	for m in d.get("miradores", []):
		if m.has("on") and not podiums.has(int(m.get("on", -1))):
			out.append("mirador %s: podium %s not found" % [m["id"], m.get("on")])
	# C1: generated buildings (rows), heroes, street segments
	for h in d.get("heroes", []):
		var id := int(h.get("id", -1))
		if id <= 0 or ids.has(id):
			out.append("hero: id %s missing or duplicated" % h.get("id"))
		ids[id] = true
	var bl: Variant = d.get("buildings", {})
	if bl is Dictionary:
		var f: Array = (bl as Dictionary).get("fields", [])
		if f.size() < 10 or str(f[0]) != "id" or str(f[1]) != "fam":
			out.append("buildings: unexpected fields %s" % [f])
		else:
			for r in (bl as Dictionary).get("rows", []):
				var id := int(r[0])
				if id <= 0 or ids.has(id):
					out.append("building %s: id missing or duplicated" % r[0])
				ids[id] = true
				var fam := str(r[1])
				if not BuildingAssembler.has_family(fam) or int(r[2]) < 0 or int(r[2]) >= BuildingAssembler.variant_count(fam) or int(r[3]) < 1:
					out.append("building %s: bad family / variant / floors %s" % [r[0], r])
	var st: Variant = d.get("streets", [])
	if st is Dictionary and ((st as Dictionary).get("fields", []) as Array).size() < 6:
		out.append("streets: unexpected fields")
	return out


## Floors of an assembled tower: 4 (Base) + 4 per floor group + the family's partial top group + 1 (Roof floor).
static func tower_floors(t: Dictionary) -> int:
	var f: Dictionary = _data["families"][str(t["family"])]
	return 4 + 4 * int(t["groups"]) + int(f["top_floors"]) + 1


## Extra height of an assembled tower over its family model (m): the floor groups stacked on top of the model's.
static func tower_shift(t: Dictionary) -> float:
	var f: Dictionary = _data["families"][str(t["family"])]
	return float(int(t["groups"]) - int(f["full_groups"])) * 4.0 * cm(f["floor_h"])


static func podium(id: int) -> Dictionary:
	return _podiums.get(id, {})


## Roof slab level of a podium over its base (m).
static func podium_roof(p: Dictionary) -> float:
	return cm(p["ground_h"]) + float(int(p["floors"]) - 1) * cm(p["floor_h"])


# ------------------------------------------------------------------ static index (layout, seed independent)
static func _index() -> void:
	_static_by_chunk.clear()
	_footprints.clear()
	_clear.clear()
	_podiums.clear()
	_foot_by_chunk.clear()
	_seg_by_chunk.clear()
	_clear_by_chunk.clear()
	_buildings.clear()
	_heroes.clear()
	for c in _data.get("clear", []):
		_clear.append(rect_of(c))
		_bucket(_clear_by_chunk, rect_of(c), rect_of(c))
	for p in _data.get("podiums", []):
		_podiums[int(p["id"])] = p
		var it := {"k": Kind.PODIUM, "id": int(p["id"]), "pos": v2(p["pos"]), "yaw": float(p.get("yaw", 0.0)),
			"size": v2(p["size"]), "floors": int(p["floors"]), "ground_h": cm(p["ground_h"]), "floor_h": cm(p["floor_h"]),
			"style": str(p.get("style", "concrete")), "generator": bool(p.get("generator", false)), "stair": p.get("stair", {}),
			"wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(p["id"]), 0)}
		_add(it)
		_footprints.append([_obb_bounds(it["pos"], it["size"], it["yaw"]), Kind.PODIUM])
		_add_foot(obb(it["pos"], it["size"], it["yaw"]), Kind.PODIUM, int(p["id"]), false)
	for t in _data.get("towers", []):
		var fam: Dictionary = _data["families"][str(t["family"])]
		var it := {"k": Kind.TOWER, "id": int(t["id"]), "pos": v2(t["pos"]), "yaw": float(t.get("yaw", 0.0)),
			"family": str(t["family"]), "model": str(fam["model"]), "groups": int(t["groups"]), "on": int(t["on"]),
			"floors": tower_floors(t), "shift": tower_shift(t), "generator": bool(t.get("generator", false)),
			"wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(t["id"]), 0)}
		_add(it)
	for v in _data.get("vehicles", []):
		var it := _model_item(Kind.VEHICLE, v, v2(v["pos"]), float(v.get("yaw", 0.0)), 0)
		it["variant"] = str(v.get("variant", "snowed"))
		_add(it)
		var sz := model_size(str(v["model"]))
		_footprints.append([_obb_bounds(it["pos"], Vector2(sz.x, sz.z), it["yaw"]), Kind.VEHICLE])
		_add_foot(obb(it["pos"], Vector2(sz.x, sz.z), it["yaw"]), Kind.VEHICLE, int(v["id"]), false)
	for p in _data.get("props", []):
		_add(_model_item(Kind.PROP, p, v2(p["pos"]), float(p.get("yaw", 0.0)), 0))
	for r in _data.get("rows", []):
		var a := v2(r["from"])
		var b := v2(r["to"])
		var step := cm(r["step"])
		var n := int(floor(a.distance_to(b) / step + 0.001)) + 1
		for i in n:
			var p := a + (b - a).normalized() * step * float(i) if a.distance_to(b) > 0.01 else a
			_add(_model_item(Kind.PROP, r, p, float(r.get("yaw", 0.0)), i))
	_bridge = _data.get("bridge", {})
	if not _bridge.is_empty():
		var x0 := cm(_bridge["x_from"])
		var x1 := cm(_bridge["x_to"])
		var z := cm(_bridge["axis_z"])
		var cz := WorldConst.chunk_of(z)
		for cx in range(WorldConst.chunk_of(x0), WorldConst.chunk_of(x1) + 1):
			var r := WorldConst.chunk_rect(cx, cz)
			var sx0 := maxf(x0, r.position.x)
			var sx1 := minf(x1, r.end.x)
			if sx1 - sx0 < 0.01:
				continue
			var key := WorldConst.key(cx, cz)
			if not _static_by_chunk.has(key):
				_static_by_chunk[key] = []
			(_static_by_chunk[key] as Array).append({"k": Kind.BRIDGE, "id": int(_bridge["id"]), "x0": sx0, "x1": sx1, "pos": Vector2((sx0 + sx1) * 0.5, z),
				"wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(_bridge["id"]), cx)})
	for j in _data.get("jams", []):
		var x0 := cm(j["x_from"])
		var x1 := cm(j["x_to"])
		for lane in j["lanes"]:
			var z := cm(j["axis_z"]) + cm(lane)
			for cx in range(WorldConst.chunk_of(x0 - 8.0), WorldConst.chunk_of(x1 + 8.0) + 1):
				_chunks_with_jam[WorldConst.key(cx, WorldConst.chunk_of(z))] = true
	# C1: generated buildings (rows), heroes, street segments
	var bl: Variant = _data.get("buildings", {})
	if bl is Dictionary:
		for r in (bl as Dictionary).get("rows", []):
			var fam := str(r[1])
			var vi := int(r[2])
			var flags := int(r[8])
			var it := {"k": Kind.BUILDING, "id": int(r[0]), "fam": fam, "var": vi, "floors": int(r[3]), "pos": Vector2(cm(r[4]), cm(r[5])),
				"yaw": float(r[6]) / 100.0, "pal": int(r[7]), "ent": (flags & 1) != 0, "generator": (flags & 2) != 0, "district": int(r[9]),
				"size": BuildingAssembler.size_of(fam, vi), "wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(r[0]), 0)}
			_add(it)
			_buildings[int(r[0])] = it
			_add_foot(obb(it["pos"], it["size"], it["yaw"]), Kind.BUILDING, int(r[0]), bool(it["ent"]))
	for h in _data.get("heroes", []):
		_heroes[int(h["id"])] = h
		var it := {"k": Kind.HERO, "id": int(h["id"]), "pos": v2(h["pos"]), "yaw": float(h.get("yaw", 0.0)), "size": v2(h["size"]),
			"floors": int(h["floors"]), "wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(h["id"]), 0)}
		_add(it)
		_add_foot(obb(it["pos"], it["size"], it["yaw"]), Kind.HERO, int(h["id"]), true)
	var st: Variant = _data.get("streets", [])
	if st is Dictionary:
		for r in (st as Dictionary).get("rows", []):
			var a := Vector2(cm(r[0]), cm(r[1]))
			var b := Vector2(cm(r[2]), cm(r[3]))
			var w := cm(r[4])
			var bb := Rect2(a, Vector2.ZERO).expand(b).grow(w * 0.5 + 0.5)
			_bucket(_seg_by_chunk, bb, [a, b, w, int(r[5]), bb])
	_dress_lamps()


static func _model_item(kind: int, src: Dictionary, pos: Vector2, yaw: float, index: int) -> Dictionary:
	var m := str(src["model"])
	var md: Dictionary = _data["models"][m]
	var it := {"k": kind, "id": int(src["id"]), "model": m, "dir": str(md.get("dir", "props")), "pos": pos, "yaw": yaw,
		"lamp": bool(src.get("lamp", false)),
		"wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, int(src["id"]), index)}
	return it


static func _add(it: Dictionary) -> void:
	var p: Vector2 = it["pos"]
	var key := WorldConst.key(WorldConst.chunk_of(p.x), WorldConst.chunk_of(p.y))
	if not _static_by_chunk.has(key):
		_static_by_chunk[key] = []
	(_static_by_chunk[key] as Array).append(it)


## Appends `rec` to every chunk bucket of `idx` that `bounds` touches.
static func _bucket(idx: Dictionary, bounds: Rect2, rec: Variant) -> void:
	for cz in range(WorldConst.chunk_of(bounds.position.y), WorldConst.chunk_of(bounds.end.y) + 1):
		for cx in range(WorldConst.chunk_of(bounds.position.x), WorldConst.chunk_of(bounds.end.x) + 1):
			var k := WorldConst.key(cx, cz)
			if not idx.has(k):
				idx[k] = []
			(idx[k] as Array).append(rec)


static func _add_foot(q: PackedVector2Array, kind: int, id: int, indoor: bool) -> void:
	var bb := Rect2(q[0], Vector2.ZERO)
	for p in q:
		bb = bb.expand(p)
	_bucket(_foot_by_chunk, bb, [q, kind, id, bb, indoor])


## Corners of a footprint `size` centred at `pos` turned by `yaw_deg` (the building frame: world = Basis(UP, yaw)·local).
static func obb(pos: Vector2, size: Vector2, yaw_deg: float) -> PackedVector2Array:
	var a := deg_to_rad(yaw_deg)
	var ax := Vector2(cos(a), -sin(a))
	var az := Vector2(sin(a), cos(a))
	var hx := size.x * 0.5
	var hz := size.y * 0.5
	return PackedVector2Array([pos - ax * hx - az * hz, pos + ax * hx - az * hz, pos + ax * hx + az * hz, pos - ax * hx + az * hz])


## Is the plan point inside the convex quad `q` grown by `margin`?
static func in_quad(q: PackedVector2Array, p: Vector2, margin: float = 0.0) -> bool:
	for i in 4:
		var a := q[i]
		var b := q[(i + 1) % 4]
		var e := (b - a).normalized()
		# the quads run counter-clockwise seen from above in x/z (z south): the inside is to the right of a→b
		var nrm := Vector2(-e.y, e.x)
		if (p - a).dot(nrm) < -margin:
			return false
	return true


## World AABB (xz) of a footprint `size` centred at `pos`, turned by `yaw_deg`.
static func _obb_bounds(pos: Vector2, size: Vector2, yaw_deg: float) -> Rect2:
	var a := deg_to_rad(yaw_deg)
	var ex := absf(cos(a)) * size.x * 0.5 + absf(sin(a)) * size.y * 0.5
	var ez := absf(sin(a)) * size.x * 0.5 + absf(cos(a)) * size.y * 0.5
	return Rect2(pos - Vector2(ex, ez), Vector2(ex, ez) * 2.0)


## [width x, height y, length z] of a model (m) for colliders and fallbacks.
static func model_size(m: String) -> Vector3:
	var md: Dictionary = _data.get("models", {}).get(m, {})
	var s: Array = md.get("size", [100, 100, 100])
	return Vector3(cm(s[0]), cm(s[1]), cm(s[2]))


static func model_info(m: String) -> Dictionary:
	return _data.get("models", {}).get(m, {})


## Chunks that have city items (static layout or a jam lane): the streamer / tests.
static func chunk_keys() -> Array:
	var out := {}
	for k in _static_by_chunk:
		out[k] = true
	for k in _chunks_with_jam:
		out[k] = true
	var arr := out.keys()
	arr.sort()
	return arr


static func has_chunk(cx: int, cz: int) -> bool:
	var k := WorldConst.key(cx, cz)
	return _static_by_chunk.has(k) or _chunks_with_jam.has(k)


# ------------------------------------------------------------------ queries used by the ChunkJob (worker threads)
## Is (x, z) inside the city area where the procedural scatter is not placed (clear rects, building footprints,
## painted streets / sidewalks / plazas)? Chunk-indexed (worker threads: the ChunkJob scatter filter).
static func is_cleared(x: float, z: float) -> bool:
	var p := Vector2(x, z)
	var k := WorldConst.key(WorldConst.chunk_of(x), WorldConst.chunk_of(z))
	for r in _clear_by_chunk.get(k, []):
		if (r as Rect2).has_point(p):
			return true
	for f in _foot_by_chunk.get(k, []):
		if (f[3] as Rect2).grow(1.5).has_point(p) and in_quad(f[0], p, 1.5):
			return true
	for sg in _seg_by_chunk.get(k, []):
		if (sg[4] as Rect2).has_point(p) and _seg_dist(p, sg[0], sg[1]) <= float(sg[2]) * 0.5 + 1.0:
			return true
	return false


## Does anything of the city that clears the scatter reach `rect`?
static func clears_rect(rect: Rect2) -> bool:
	for cz in range(WorldConst.chunk_of(rect.position.y), WorldConst.chunk_of(rect.end.y) + 1):
		for cx in range(WorldConst.chunk_of(rect.position.x), WorldConst.chunk_of(rect.end.x) + 1):
			var k := WorldConst.key(cx, cz)
			if _clear_by_chunk.has(k) or _foot_by_chunk.has(k) or _seg_by_chunk.has(k):
				return true
	return false


## Is (x, z) inside a building or a static vehicle footprint (+ margin)? Zombie spawns, tests. Chunk-indexed.
static func occupied(x: float, z: float, margin: float = 0.5) -> bool:
	var p := Vector2(x, z)
	for cz in range(WorldConst.chunk_of(z - margin), WorldConst.chunk_of(z + margin) + 1):
		for cx in range(WorldConst.chunk_of(x - margin), WorldConst.chunk_of(x + margin) + 1):
			for f in _foot_by_chunk.get(WorldConst.key(cx, cz), []):
				if (f[3] as Rect2).grow(margin).has_point(p) and in_quad(f[0], p, margin):
					return true
	return false


## The footprint record [quad, kind, id, bounds, indoor] containing (x, z), or [] (the vertical interest filter:
## an enterable building / hero tower is «indoors»).
static func footprint_at(x: float, z: float) -> Array:
	var p := Vector2(x, z)
	for f in _foot_by_chunk.get(WorldConst.key(WorldConst.chunk_of(x), WorldConst.chunk_of(z)), []):
		if (f[3] as Rect2).has_point(p) and in_quad(f[0], p, 0.0):
			return f
	return []


## Is the world point inside a hero tower or an enterable building, above its street level (> 1.5 m over the
## terrain height `ground`)? Anything at street level counts as outdoors (the street crowd stays visible).
static func indoors(p: Vector3, ground: float) -> bool:
	var f := footprint_at(p.x, p.z)
	return not f.is_empty() and bool(f[4]) and p.y > ground + 1.5


static var _base_cache: Dictionary = {}   # footprint (kind, id) -> base height (server: the vertical filter)


## Is the world point inside a hero tower or an enterable building, more than 1.5 m over its base (its upper floors)?
## The ZombieNet vertical interest filter (C1); the base of each footprint is computed once (main thread).
static func indoors_at(p: Vector3, hf: HeightFunction) -> bool:
	var f := footprint_at(p.x, p.z)
	if f.is_empty() or not bool(f[4]):
		return false
	var key := int(f[1]) * 1000000 + int(f[2])
	var base: float
	if _base_cache.has(key):
		base = float(_base_cache[key])
	else:
		if int(f[1]) == Kind.HERO:
			base = hero_base(hf, int(f[2]))
		else:
			var b: Dictionary = _buildings.get(int(f[2]), {})
			base = footprint_base(hf, b["pos"], b["size"], float(b["yaw"])) if not b.is_empty() else hf.height_at(p.x, p.z)
		_base_cache[key] = base
	return p.y > base + 1.5


static func _seg_dist(p: Vector2, a: Vector2, b: Vector2) -> float:
	var ab := b - a
	var l2 := ab.length_squared()
	if l2 < 1e-6:
		return p.distance_to(a)
	var t := clampf((p - a).dot(ab) / l2, 0.0, 1.0)
	return p.distance_to(a + ab * t)


## C0 format: street surface rects crossing `rect`: [Rect2, kind ("road" | "walk"), axis ("x" | "z")] ([] with C1's
## segments: paint_chunk paints those).
static func streets_in(rect: Rect2) -> Array:
	var out: Array = []
	var st: Variant = _data.get("streets", [])
	if not (st is Array):
		return out
	for s in st:
		var r := rect_of(s["rect"])
		if r.intersects(rect):
			out.append([r, str(s["kind"]), str(s.get("axis", "x"))])
	return out


## Street segments (roads, sidewalks, plazas) crossing `rect`: [a, b, width, kind, bounds].
static func segments_in(rect: Rect2) -> Array:
	var out: Array = []
	var seen := {}
	for cz in range(WorldConst.chunk_of(rect.position.y), WorldConst.chunk_of(rect.end.y) + 1):
		for cx in range(WorldConst.chunk_of(rect.position.x), WorldConst.chunk_of(rect.end.x) + 1):
			for sg in _seg_by_chunk.get(WorldConst.key(cx, cz), []):
				var id := (sg as Array).hash()
				if seen.has(id) or not (sg[4] as Rect2).intersects(rect):
					continue
				seen[id] = true
				out.append(sg)
	return out


## Paints the C1 street segments into a chunk's surface mask (CUSTOM0 packed per sample: r road 230, b packed snow
## 204, a 128 + 16·offset for the ruts): roads first, sidewalks and plazas only where there is no road bed.
## `surface` = the ChunkJob's per-sample array (N × N, origin ox, oz, 1 m samples); returns it painted (packed arrays
## are values in GDScript).
static func paint_chunk(surface: PackedInt32Array, ox: int, oz: int, n: int) -> PackedInt32Array:
	var rect := Rect2(float(ox), float(oz), float(n - 1), float(n - 1))
	var segs := segments_in(rect.grow(1.0))
	if segs.is_empty():
		return surface
	for pass_i in 2:
		for sg in segs:
			var road := int(sg[3]) == SEG_ROAD
			if road != (pass_i == 0):
				continue
			var a: Vector2 = sg[0]
			var b: Vector2 = sg[1]
			var hw := float(sg[2]) * 0.5
			var bb: Rect2 = sg[4]
			var i0 := clampi(int(ceil(bb.position.x)) - ox, 0, n - 1)
			var i1 := clampi(int(floor(bb.end.x)) - ox, 0, n - 1)
			var j0 := clampi(int(ceil(bb.position.y)) - oz, 0, n - 1)
			var j1 := clampi(int(floor(bb.end.y)) - oz, 0, n - 1)
			var ab := b - a
			var l2 := maxf(ab.length_squared(), 1e-6)
			var nrm := Vector2(-ab.y, ab.x).normalized()
			for j in range(j0, j1 + 1):
				for i in range(i0, i1 + 1):
					var p := Vector2(float(ox + i), float(oz + j))
					var t := clampf((p - a).dot(ab) / l2, 0.0, 1.0)
					var q := a + ab * t
					if p.distance_to(q) > hw:
						continue
					var k := j * n + i
					var sv := surface[k]
					if road:
						var off := (p - a).dot(nrm)
						var al := clampi(int(round(128.0 + 16.0 * off)), 1, 255)
						surface[k] = (sv & 0x00FF00) | 230 | (al << 24)
					elif (sv & 255) < 64:
						surface[k] = (sv & 0x00FF00) | (204 << 16)
	return surface


## Deck height of the Puente de Hierro at x (terrain heights at its two ends from `hf`). NAN off the bridge.
static func bridge_deck(hf: HeightFunction, x: float, z: float) -> float:
	if _bridge.is_empty():
		return NAN
	var x0 := cm(_bridge["x_from"])
	var x1 := cm(_bridge["x_to"])
	if x < x0 or x > x1 or absf(z - cm(_bridge["axis_z"])) > cm(_bridge["width"]) * 0.5 + 0.01:
		return NAN
	return deck_profile(x, bridge_ends(hf))


## [terrain height at the west end, at the east end] of the bridge (the ramps meet the ground there).
static func bridge_ends(hf: HeightFunction) -> Vector2:
	var z := cm(_bridge["axis_z"])
	return Vector2(hf.height_at(cm(_bridge["x_from"]), z), hf.height_at(cm(_bridge["x_to"]), z))


static func deck_profile(x: float, ends: Vector2) -> float:
	var x0 := cm(_bridge["x_from"])
	var x1 := cm(_bridge["x_to"])
	var h := cm(_bridge["deck_y"])
	var ramp := cm(_bridge["ramp"])
	if x < x0 + ramp:
		return lerpf(ends.x, h, clampf((x - x0) / ramp, 0.0, 1.0))
	if x > x1 - ramp:
		return lerpf(h, ends.y, clampf((x - (x1 - ramp)) / ramp, 0.0, 1.0))
	return h


static func bridge() -> Dictionary:
	return _bridge


## Base height of a podium: the lowest terrain sample of its footprint corners and centre (it never floats; the
## plinth below 0 hides the higher corners). Pure: every chunk that needs it (the podium's, a tower's) agrees.
static func podium_base(hf: HeightFunction, p_id: int) -> float:
	var p: Dictionary = _podiums.get(p_id, {})
	if p.is_empty():
		return 0.0
	var c := v2(p["pos"])
	var s := v2(p["size"]) * 0.5
	var a := deg_to_rad(float(p.get("yaw", 0.0)))
	var h := hf.height_at(c.x, c.y)
	for q in [Vector2(-1, -1), Vector2(1, -1), Vector2(1, 1), Vector2(-1, 1)]:
		var o := Vector2(q.x * s.x, q.y * s.y).rotated(-a)
		h = minf(h, hf.height_at(c.x + o.x, c.y + o.y))
	return h - 0.05


## Base height of a C1 lot: the HIGHEST terrain sample of its footprint (corners, edge midpoints, centre): the ground
## floor never sinks into the slope; the family's skirt (walls below the base) closes the downhill side. Pure.
static func footprint_base(hf: HeightFunction, pos: Vector2, size: Vector2, yaw_deg: float) -> float:
	var q := obb(pos, size, yaw_deg)
	var h := hf.height_at(pos.x, pos.y)
	for i in 4:
		h = maxf(h, hf.height_at(q[i].x, q[i].y))
		var m := (q[i] + q[(i + 1) % 4]) * 0.5
		h = maxf(h, hf.height_at(m.x, m.y))
	return h + 0.02


## A BUILDING item by lot id ({} when unknown), without its height.
static func building(id: int) -> Dictionary:
	return _buildings.get(id, {})


static func building_ids() -> Array:
	var k := _buildings.keys()
	k.sort()
	return k


## The hero tower record of the file (id → {name, pos, size, yaw, floors, ground_h, floor_h, furnished, …}).
static func hero(id: int) -> Dictionary:
	return _heroes.get(id, {})


static func heroes() -> Array:
	return _data.get("heroes", [])


## Base height of a hero tower (the same rule as the lots).
static func hero_base(hf: HeightFunction, id: int) -> float:
	var h: Dictionary = _heroes.get(id, {})
	if h.is_empty():
		return 0.0
	return footprint_base(hf, v2(h["pos"]), v2(h["size"]), float(h.get("yaw", 0.0)))


## The street graph: {"nodes": [[x_cm, z_cm]…], "edges": [[a, b, width_cm, kind]…]} (hordes L2, convoys, M9b).
static func graph() -> Dictionary:
	return _data.get("graph", {})


## District zones of the file: [{"id": LocationInfo id, "district", "rect"}].
static func districts() -> Array:
	return _data.get("districts", [])


## District id of a point ("" outside the generated districts; Las Torres wins over the ensanche around it).
static func district_at(x: float, z: float) -> String:
	var best := ""
	for d in districts():
		if rect_of(d["rect"]).has_point(Vector2(x, z)):
			if best == "" or str(d["district"]) == "las_torres":
				best = str(d["district"])
	return best


## Every city item of chunk (cx, cz) with its heights, for the world seed (layout + seeded jam dressing).
## `height` = Callable(x, z) -> float for points inside the chunk (ChunkJob.height_local: bilinear on its samples).
static func chunk_items(hf: HeightFunction, cx: int, cz: int, height: Callable) -> Array:
	var key := WorldConst.key(cx, cz)
	var out: Array = []
	if not is_loaded():
		return out
	var ends := Vector2(NAN, NAN)
	var need_ends := false
	for it in _static_by_chunk.get(key, []):
		var e: Dictionary = (it as Dictionary).duplicate()
		var p: Vector2 = e["pos"]
		match int(e["k"]):
			Kind.PODIUM:
				e["y"] = podium_base(hf, int(e["id"]))
			Kind.TOWER:
				var pod: Dictionary = _podiums[int(e["on"])]
				e["y"] = podium_base(hf, int(e["on"])) + podium_roof(pod)
			Kind.BUILDING, Kind.HERO:
				e["y"] = footprint_base(hf, e["pos"], e["size"], float(e["yaw"]))
				e["seed"] = hf.world_seed   # the seeded dressing (door / loot wids) is built from it on every peer
			Kind.BRIDGE:
				need_ends = true
			_:
				e["y"] = NAN
		out.append(e)
	var jams: Array = []
	if _chunks_with_jam.has(key):
		jams = jam_items(hf.world_seed, WorldConst.chunk_rect(cx, cz))
		out.append_array(jams)
	if _seg_by_chunk.has(key):
		out.append_array(street_items(hf.world_seed, WorldConst.chunk_rect(cx, cz)))
	for e in out:
		if int(e["k"]) == Kind.BRIDGE:
			continue
		if e.has("y") and not is_nan(float(e["y"])):
			continue
		var p: Vector2 = e["pos"]
		if not _bridge.is_empty() and absf(p.y - cm(_bridge["axis_z"])) <= cm(_bridge["width"]) * 0.5 and p.x >= cm(_bridge["x_from"]) and p.x <= cm(_bridge["x_to"]):
			need_ends = true
	if need_ends:
		ends = bridge_ends(hf)
	for e in out:
		var p: Vector2 = e["pos"]
		if int(e["k"]) == Kind.BRIDGE:
			e["ends"] = ends
			e["y"] = deck_profile(p.x, ends)
			continue
		if e.has("y") and not is_nan(float(e["y"])):
			continue
		var on_deck := not _bridge.is_empty() and absf(p.y - cm(_bridge["axis_z"])) <= cm(_bridge["width"]) * 0.5 \
			and p.x >= cm(_bridge["x_from"]) and p.x <= cm(_bridge["x_to"])
		e["y"] = deck_profile(p.x, ends) if on_deck else float(height.call(p.x, p.y))
	return out


## Items (no heights) of the chunks around `rect` whose footprint may reach it, + the jam cars in it: contact AO.
static func items_near(seed_v: int, rect: Rect2) -> Array:
	var out: Array = []
	if not is_loaded():
		return out
	var g := rect.grow(40.0)
	for cz in range(WorldConst.chunk_of(g.position.y), WorldConst.chunk_of(g.end.y) + 1):
		for cx in range(WorldConst.chunk_of(g.position.x), WorldConst.chunk_of(g.end.x) + 1):
			for it in _static_by_chunk.get(WorldConst.key(cx, cz), []):
				out.append(it)
	for j in jam_items(seed_v, rect.grow(4.0)):
		out.append(j)
	for j in street_items(seed_v, rect.grow(4.0)):
		out.append(j)
	return out


## Jam cars (seeded dressing) whose centre lies in `rect`. Pure: hash64(seed, GEN_CITY, jam id, lane, slot).
static func jam_items(seed_v: int, rect: Rect2) -> Array:
	var out: Array = []
	for j in _data.get("jams", []):
		var x0 := cm(j["x_from"])
		var x1 := cm(j["x_to"])
		if rect.end.x < x0 - 8.0 or rect.position.x > x1 + 8.0:
			continue
		var models: Dictionary = j["models"]
		var variants: Dictionary = j["variants"]
		var facing := float(FACING.get(str(j.get("facing", "west")), -90.0))
		var gap: Array = j["gap"]
		var lanes: Array = j["lanes"]
		for li in lanes.size():
			var z := cm(j["axis_z"]) + cm(lanes[li])
			if z < rect.position.y - 3.0 or z > rect.end.y + 3.0:
				continue
			# the queue's head is the end it faces (west: x_from); cars stack back from it
			var cursor := 0.0
			var length := x1 - x0
			var slot := 0
			while cursor < length and slot < 400:
				var h := WorldConst.hash64(seed_v, GEN_CITY, int(j["id"]), li, slot)
				slot += 1
				var m := _pick(models, WorldConst.unit(WorldConst.hash64(h, 1)))
				var sz := model_size(m)
				var g := cm(gap[0]) + WorldConst.unit(WorldConst.hash64(h, 3)) * (cm(gap[1]) - cm(gap[0]))
				if WorldConst.unit(WorldConst.hash64(h, 0)) < float(j.get("skip", 0.0)):
					cursor += sz.z + g   # an empty place in the queue
					continue
				var along := cursor + sz.z * 0.5
				cursor += sz.z + g
				if along > length:
					break
				var x := x0 + along if facing < 0.0 else x1 - along
				var lat := (WorldConst.unit(WorldConst.hash64(h, 4)) - 0.5) * 2.0 * cm(j.get("jitter", 0))
				var p := Vector2(x, z + lat)
				if not rect.has_point(p):
					continue
				var yaw := facing + (WorldConst.unit(WorldConst.hash64(h, 5)) - 0.5) * 2.0 * float(j.get("yaw_jitter", 0.0))
				if WorldConst.unit(WorldConst.hash64(h, 6)) < float(j.get("askew", 0.0)):
					yaw += (20.0 + 20.0 * WorldConst.unit(WorldConst.hash64(h, 7))) * (1.0 if (h >> 9) & 1 == 1 else -1.0)
				var v := _pick(variants, WorldConst.unit(WorldConst.hash64(h, 2)))
				if _blocked(p, sz):
					continue
				var md: Dictionary = _data["models"][m]
				out.append({"k": Kind.VEHICLE, "id": int(j["id"]), "model": m, "dir": str(md.get("dir", "vehicles")), "variant": v,
					"pos": p, "yaw": snappedf(yaw, 0.01), "lamp": false, "jam": true, "wid": WorldConst.hash64(seed_v, GEN_CITY, int(j["id"]), li, slot)})
	return out


# ------------------------------------------------------------------ street dressing (C1)
static func _dress_cfg(district: String) -> Dictionary:
	return ((_data.get("dressing", {}) as Dictionary).get("districts", {}) as Dictionary).get(district, {})


## Identity of a street segment (its cm end points): the seeded dressing does not depend on which chunk asks.
static func _seg_key(a: Vector2, b: Vector2) -> int:
	return WorldConst.hash64(roundi(a.x * 100.0), roundi(a.y * 100.0), roundi(b.x * 100.0), roundi(b.y * 100.0))


## Street lamps along the roads of the districts (layout, at load): `lamp` model of the district every `lamp_step`,
## on one side (`lamp_sides` 1, the side picked by the segment) or both, on the sidewalk `lamp_curb` beyond the road
## edge, arm over the road; none within `end_clear` of a crossing, on a footprint or near another lamp.
static func _dress_lamps() -> void:
	var dr: Dictionary = _data.get("dressing", {})
	var st: Variant = _data.get("streets", [])
	if dr.is_empty() or not (st is Dictionary):
		return
	var end_clear := cm(dr.get("end_clear", 700))
	var curb := cm(dr.get("lamp_curb", 60))
	var si := -1
	for r in (st as Dictionary).get("rows", []):
		si += 1
		if int(r[5]) != SEG_ROAD:
			continue
		var a := Vector2(cm(r[0]), cm(r[1]))
		var b := Vector2(cm(r[2]), cm(r[3]))
		var w := cm(r[4])
		var mid := (a + b) * 0.5
		var cfg := _dress_cfg(district_at(mid.x, mid.y))
		if not cfg.has("lamp"):
			continue
		var m := str(cfg["lamp"])
		var md: Dictionary = (_data.get("models", {}) as Dictionary).get(m, {})
		var step := cm(cfg.get("lamp_step", 3000))
		var length := a.distance_to(b)
		if md.is_empty() or length < end_clear * 2.0 + 1.0:
			continue
		var d := (b - a) / length
		var nrm := Vector2(-d.y, d.x)
		var sides: Array = [1.0, -1.0] if int(cfg.get("lamp_sides", 1)) >= 2 else [1.0 if (_seg_key(a, b) & 1) == 0 else -1.0]
		var n := int(floor((length - end_clear * 2.0) / step)) + 1
		var off := (length - float(n - 1) * step) * 0.5
		for side in sides:
			for i in n:
				var p := a + d * (off + step * float(i)) + nrm * float(side) * (w * 0.5 + curb)
				if occupied(p.x, p.y, 0.5) or _lamp_near(p, step * 0.45) \
						or _road_hit(p, segments_in(Rect2(p - Vector2(12, 12), Vector2(24, 24))), a, b, 1.0):
					continue
				var to_road := -nrm * float(side)
				_add({"k": Kind.PROP, "id": DRESS_LAMP_ID + si, "model": m, "dir": str(md.get("dir", "props")), "pos": p.snapped(Vector2(0.01, 0.01)),
					"yaw": snappedf(rad_to_deg(atan2(to_road.x, to_road.y)), 0.01), "lamp": true, "dress": true,
					"wid": WorldConst.hash64(GEN_CITY, WorldConst.CITY_VERSION, DRESS_LAMP_ID + si, i * 2 + (0 if float(side) > 0.0 else 1))})


## Is `p` on the roadway (+ `margin`) of a road other than the segment a–b? (The painted segments run the whole length
## of a street: the dressing must skip the crossings.)
static func _road_hit(p: Vector2, segs: Array, a: Vector2, b: Vector2, margin: float) -> bool:
	for t in segs:
		if int(t[3]) != SEG_ROAD or ((t[0] as Vector2) == a and (t[1] as Vector2) == b):
			continue
		if _seg_dist(p, t[0], t[1]) < float(t[2]) * 0.5 + margin:
			return true
	return false


static func _lamp_near(p: Vector2, r: float) -> bool:
	for cz in range(WorldConst.chunk_of(p.y - r), WorldConst.chunk_of(p.y + r) + 1):
		for cx in range(WorldConst.chunk_of(p.x - r), WorldConst.chunk_of(p.x + r) + 1):
			for it in _static_by_chunk.get(WorldConst.key(cx, cz), []):
				if bool(it.get("lamp", false)) and (it["pos"] as Vector2).distance_to(p) < r:
					return true
	return false


## The seeded street dressing whose centre lies in `rect` (pure: the same on every peer): cars parked along both
## curbs (or one, `park_sides`) of the roads ≥ `min_road` wide, one `slot` each with probability `park` (district
## `cars` / `variants` weights), parallel to the curb in the direction of traffic (right-hand); furniture on the
## sidewalks every `prop_step` with probability `prop_p` (district `props`). Nothing on a footprint (1.3 m clear of the
## facades for the furniture), nothing within `end_clear` of a segment's end nor on the roadway of a crossing road.
static func street_items(seed_v: int, rect: Rect2) -> Array:
	var out: Array = []
	var dr: Dictionary = _data.get("dressing", {})
	if dr.is_empty():
		return out
	var slot := cm(dr.get("slot", 650))
	var end_clear := cm(dr.get("end_clear", 700))
	var curb := cm(dr.get("curb", 130))
	var min_road := cm(dr.get("min_road", 700))
	var models: Dictionary = _data.get("models", {})
	var near := segments_in(rect.grow(14.0))
	for sg in segments_in(rect.grow(1.0)):
		var a: Vector2 = sg[0]
		var b: Vector2 = sg[1]
		var w := float(sg[2])
		var kind := int(sg[3])
		var length := a.distance_to(b)
		if length < end_clear * 2.0 + 1.0:
			continue
		var mid := (a + b) * 0.5
		var cfg := _dress_cfg(district_at(mid.x, mid.y))
		if cfg.is_empty():
			continue
		var sk := _seg_key(a, b)
		var d := (b - a) / length
		var nrm := Vector2(-d.y, d.x)
		if kind == SEG_ROAD and w >= min_road and float(cfg.get("park", 0.0)) > 0.0:
			var sides: Array = [1.0, -1.0] if int(cfg.get("park_sides", 1)) >= 2 else [-1.0 if (sk & 2) != 0 else 1.0]
			var n := int(floor((length - end_clear * 2.0) / slot)) + 1
			for side in sides:
				for i in n:
					var h := WorldConst.hash64(seed_v, GEN_CITY, sk, 1 if float(side) > 0.0 else 2, i)
					if WorldConst.unit(h) >= float(cfg["park"]):
						continue
					var m := _pick(cfg["cars"], WorldConst.unit(WorldConst.hash64(h, 1)))
					var sz := model_size(m)
					var along := end_clear + slot * float(i) + (WorldConst.unit(WorldConst.hash64(h, 3)) - 0.5) * 0.6
					var lat := w * 0.5 - curb - (WorldConst.unit(WorldConst.hash64(h, 4)) - 0.5) * 0.3
					var p := a + d * along + nrm * float(side) * lat
					if not rect.has_point(p) or occupied(p.x, p.y, maxf(sz.x, 1.0) * 0.5) or _road_hit(p, near, a, b, sz.z * 0.5 + 2.5):
						continue
					var fwd := d * float(side)
					var yaw := rad_to_deg(atan2(fwd.x, fwd.y)) + (WorldConst.unit(WorldConst.hash64(h, 5)) - 0.5) * 6.0
					out.append({"k": Kind.VEHICLE, "id": DRESS_PARK_ID, "model": m, "dir": str((models.get(m, {}) as Dictionary).get("dir", "vehicles")),
						"variant": _pick(cfg["variants"], WorldConst.unit(WorldConst.hash64(h, 2))), "pos": p.snapped(Vector2(0.01, 0.01)),
						"yaw": snappedf(yaw, 0.01), "lamp": false, "parked": true, "wid": h})
		elif kind == SEG_WALK and float(cfg.get("prop_p", 0.0)) > 0.0:
			var step := cm(cfg.get("prop_step", 1800))
			var n := int(floor((length - end_clear * 2.0) / step)) + 1
			for i in n:
				var h := WorldConst.hash64(seed_v, GEN_CITY, sk, 3, i)
				if WorldConst.unit(h) >= float(cfg["prop_p"]):
					continue
				var m := _pick(cfg["props"], WorldConst.unit(WorldConst.hash64(h, 1)))
				var sz := model_size(m)
				if minf(sz.x, sz.z) > w * 0.5:
					continue   # a bus stop needs a wide sidewalk
				var along := end_clear + step * float(i) + (WorldConst.unit(WorldConst.hash64(h, 3)) - 0.5) * step * 0.4
				var lat := (WorldConst.unit(WorldConst.hash64(h, 4)) - 0.5) * maxf(w - 1.2, 0.0) * 0.5
				var p := a + d * minf(along, length - end_clear) + nrm * lat
				if not rect.has_point(p) or occupied(p.x, p.y, 1.3) or _lamp_near(p, 1.2) or _road_hit(p, near, a, b, 0.8):
					continue
				var yaw := rad_to_deg(atan2(d.x, d.y)) + (90.0 if (h >> 12) & 1 == 1 else -90.0) + (WorldConst.unit(WorldConst.hash64(h, 5)) - 0.5) * 20.0
				out.append({"k": Kind.PROP, "id": DRESS_PROP_ID, "model": m, "dir": str((models.get(m, {}) as Dictionary).get("dir", "props")),
					"pos": p.snapped(Vector2(0.01, 0.01)), "yaw": snappedf(yaw, 0.01), "lamp": false, "wid": h})
	return out


## A jam car would sit on a fixed vehicle or a barrier (circle test with the fixed items of its chunk and the next).
static func _blocked(p: Vector2, sz: Vector3) -> bool:
	var r := maxf(sz.x, sz.z) * 0.5
	for dx in [-1, 0, 1]:
		var key := WorldConst.key(WorldConst.chunk_of(p.x) + dx, WorldConst.chunk_of(p.y))
		for it in _static_by_chunk.get(key, []):
			var k := int(it["k"])
			if k != Kind.VEHICLE and k != Kind.PROP:
				continue
			var s2 := model_size(str(it["model"]))
			var r2 := maxf(s2.x, s2.z) * 0.5
			if (it["pos"] as Vector2).distance_to(p) < (r + r2) * 0.8:
				return true
	return false


static func _pick(weights: Dictionary, u: float) -> String:
	var total := 0.0
	for k in weights:
		total += float(weights[k])
	var acc := 0.0
	var keys := weights.keys()
	for k in keys:
		acc += float(weights[k]) / total
		if u < acc:
			return str(k)
	return str(keys[keys.size() - 1])


# ------------------------------------------------------------------ world-level records (not streamed)
static func miradores() -> Array:
	return _data.get("miradores", [])


static func camera_zones() -> Array:
	return _data.get("camera_zones", [])


static func silhouettes() -> Dictionary:
	return _data.get("silhouettes", {})


static func families() -> Dictionary:
	return _data.get("families", {})


static func towers() -> Array:
	return _data.get("towers", [])


static func podiums() -> Array:
	return _data.get("podiums", [])


## Power of the city v0: grid level (0 = blackout) and the lot ids with a generator.
static func power() -> Dictionary:
	return _data.get("power", {"grid": 0.0, "generators": []})


## Canonical text of every item of the city for a seed (tests: client vs server): one line per item, cm integers.
static func items_digest(hf: HeightFunction) -> String:
	var hc := HashingContext.new()
	hc.start(HashingContext.HASH_SHA256)
	var n := 0
	for key in chunk_keys():
		var cx := WorldConst.key_cx(key)
		var cz := WorldConst.key_cz(key)
		for e in chunk_items(hf, cx, cz, func(x: float, z: float) -> float: return hf.height_at(x, z)):
			hc.update(item_line(e).to_utf8_buffer())
			n += 1
	return "%s items=%d" % [hc.finish().hex_encode(), n]


## Digest of the seeded dressing of the first `n` enterable lots (C1 acceptance «vestido de 50 parcelas»): per lot
## its wid, its door's wid (KitDoor.wid_for) and each loot container's wid and table (LootSpawns: hash64(seed,
## GEN_LOOT, lot wid, i + 1); the table is the lot's hash pick) — what every peer builds without replicating a node.
static func lot_digest(seed_v: int, n: int = 50) -> String:
	var hc := HashingContext.new()
	hc.start(HashingContext.HASH_SHA256)
	var done := 0
	for id in building_ids():
		if done >= n:
			break
		var b: Dictionary = _buildings[id]
		if not bool(b["ent"]):
			continue
		var bw := int(b["wid"])
		var fam := str(b["fam"])
		var line := "%d %x %x" % [int(id), bw, KitDoor.wid_for(seed_v, bw, 0)]
		var tables: Array = BuildingAssembler.SHOP_TABLES.get(fam, [&"house"])
		var sp: Array = BuildingAssembler.spawns(BuildingAssembler.spec(fam, int(b["var"])))
		for i in sp.size():
			var tbl: StringName = tables[posmod(int(WorldConst.hash64(bw, 17, i) & 0xFFFF), tables.size())]
			line += " %x:%s" % [WorldConst.hash64(seed_v, Loot.GEN_LOOT, bw, i + 1), tbl]
		hc.update((line + "\n").to_utf8_buffer())
		done += 1
	return "%s lots=%d" % [hc.finish().hex_encode(), done]


static func item_line(e: Dictionary) -> String:
	var p: Vector2 = e["pos"]
	var what := str(e.get("model", e.get("family", "")))
	if int(e["k"]) == Kind.BUILDING:
		what = "%s/%d/%d/%d/%d" % [e["fam"], int(e["var"]), int(e["floors"]), int(e["pal"]), 1 if bool(e["ent"]) else 0]
	return "%d %d %s %s %d %d %d %d %d\n" % [int(e["k"]), int(e["id"]), what, str(e.get("variant", "")),
		int(round(p.x * 100.0)), int(round(p.y * 100.0)), int(round(float(e.get("y", 0.0)) * 100.0)), int(round(float(e.get("yaw", 0.0)) * 100.0)), int(e["wid"])]
