#!/usr/bin/env bash
# Determinism gate (PLAN M3, R3): the same 50 chunks generated by two separate processes through the server
# path (no visuals, main thread) and the client path (mesh arrays + MultiMesh buffers, worker threads) must hash
# identically (heights to the cm, surface mask, scatter entries + wids, POI props, height_at at 200 points).
set -uo pipefail
cd "$(dirname "$0")/.."
OUT="${DET_OUT:-/tmp/ventisca_det}"
mkdir -p "$OUT"
NOISE="ALSA lib|pulse|XDG_RUNTIME|libudev|udev"
godot --headless --path . -s tests/determinism.gd ++ --role=server --out="$OUT/server.txt" 2>&1 | grep -v -E "$NOISE" | grep -E "determinism|ERROR|SCRIPT"
godot --headless --path . -s tests/determinism.gd ++ --role=client --out="$OUT/client.txt" 2>&1 | grep -v -E "$NOISE" | grep -E "determinism|ERROR|SCRIPT"
if [ ! -s "$OUT/server.txt" ] || [ ! -s "$OUT/client.txt" ]; then echo "DETERMINISM FAILED: missing output"; exit 1; fi
if diff "$OUT/server.txt" "$OUT/client.txt" > "$OUT/diff.txt"; then
  tail -n 1 "$OUT/server.txt"
  echo "DETERMINISM OK"
else
  head -n 20 "$OUT/diff.txt"
  echo "DETERMINISM FAILED"
  exit 1
fi
