extends Node
## Global signal bus. No logic lives here.

# time & weather
signal time_changed(day: int, hour: float, is_night: bool)
signal day_started(day: int)
signal night_started(day: int)
signal weather_changed(weather: StringName)
signal blizzard_warning(seconds: float)
signal world_ready()
signal region_changed(region_name: String)
# player
signal stat_changed(stat: StringName, value: float, max_value: float)
signal player_damaged(amount: float, source: StringName)
signal player_died(cause: StringName)
signal shelter_changed(inside: bool)
signal torch_toggled(lit: bool)
signal tool_changed(tool_id: StringName)
signal camera_shake(strength: float)
signal camera_yaw_changed(yaw_deg: float)
signal hover_changed(label: String)
signal placement_mode(active: bool)
# inventory & crafting
signal inventory_changed()
signal item_picked_up(item_id: StringName, amount: int)
signal item_consumed(item_id: StringName)
signal crafted(recipe_id: StringName)
signal craft_failed(reason: String)
signal storage_opened(storage: Node)
signal storage_closed()
# world objects
signal tree_hit(tree: Node, hits: int, total: int)
signal tree_felled(variant: String)
signal campfire_placed(campfire: Node)
signal campfire_lit(campfire: Node)
signal campfire_extinguished(campfire: Node)
signal stove_fueled()
signal stove_changed(lit: bool)
signal wolf_spawned(wolf: Node)
signal wolf_died(wolf: Node)
# quests & flow
signal quest_updated(state: Dictionary)
signal quest_step_completed(step_index: int)
signal quest_day_completed(day: int)
signal notify(text: String, seconds: float)
signal game_paused(paused: bool)
signal game_over(days: int, hours: int, cause: StringName)
signal game_won(days: int)
# network / multiplayer (M1)
signal local_player_ready(player: Node)
signal player_respawned()
signal chat_message(who: String, text: String)
signal hit_result(victim_peer: int, blocked: bool, reason: String)
